module.exports = function(sequelize,DataTypes){
    return sequelize.define('testcase',{
        
        area:DataTypes.STRING,
        category:DataTypes.STRING,
        subcat:DataTypes.STRING,
        owner:DataTypes.INTEGER,
        status:DataTypes.STRING,
        details:DataTypes.TEXT,
        expectation:DataTypes.TEXT,
        notes:DataTypes.TEXT,
        deskphone:DataTypes.BOOLEAN,
        sharpenq:DataTypes.BOOLEAN,
        connectphone:DataTypes.BOOLEAN,
        chrome:DataTypes.BOOLEAN,
        firefox:DataTypes.BOOLEAN,
        ctisn:DataTypes.BOOLEAN,
        ctizd:DataTypes.BOOLEAN,
        ctisfdc:DataTypes.BOOLEAN,
        android:DataTypes.BOOLEAN,
        ios:DataTypes.BOOLEAN,
        connect:DataTypes.BOOLEAN,
        quick:DataTypes.BOOLEAN,
        full:DataTypes.BOOLEAN,
        regression:DataTypes.BOOLEAN,
        automated:DataTypes.BOOLEAN,
        inboundcall:DataTypes.BOOLEAN,
        chat:DataTypes.BOOLEAN,
        email:DataTypes.BOOLEAN,
        tweet:DataTypes.BOOLEAN,
        tweetdm:DataTypes.BOOLEAN,
        facebook:DataTypes.BOOLEAN,
        sms:DataTypes.BOOLEAN,
        casein:DataTypes.BOOLEAN,
        voicemail:DataTypes.BOOLEAN,
        insights:DataTypes.BOOLEAN,
    })
}