module.exports = function(sequelize,DataTypes){
    return sequelize.define('testcase',{
        
        area:DataTypes.STRING,
        category:DataTypes.STRING,
        subcat:DataTypes.STRING,
        owner:DataTypes.INTEGER,
        status:DataTypes.STRING,
        details:DataTypes.TEXT,
        expectation:DataTypes.TEXT,
        notes:DataTypes.TEXT,
        deskphone:DataTypes.TEXT,
        sharpenq:DataTypes.TEXT,
        connectphone:DataTypes.TEXT,
        chrome:DataTypes.TEXT,
        firefox:DataTypes.TEXT,
        ctisn:DataTypes.TEXT,
        ctizd:DataTypes.TEXT,
        ctisfdc:DataTypes.TEXT,
        android:DataTypes.TEXT,
        ios:DataTypes.TEXT,
        connect:DataTypes.TEXT,
        quick:DataTypes.TEXT,
        full:DataTypes.TEXT,
        regression:DataTypes.TEXT,
        automated:DataTypes.TEXT,
        inboundcall:DataTypes.TEXT,
        chat:DataTypes.TEXT,
        email:DataTypes.TEXT,
        tweet:DataTypes.TEXT,
        tweetdm:DataTypes.TEXT,
        facebook:DataTypes.TEXT,
        sms:DataTypes.TEXT,
        casein:DataTypes.TEXT,
        voicemail:DataTypes.TEXT,
        insights:DataTypes.TEXT,
    })
}